# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define VideoAnalytics service
  ia_video_analytics:
    read_only: true
    depends_on:
      - ia_video_common
      - ia_openvino_base
    build:
      context: $PWD/../VideoAnalytics
      dockerfile: $PWD/../VideoAnalytics/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
        CMAKE_BUILD_TYPE: "Release"
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        OPENVINO_IMAGE: ${OPENVINO_IMAGE}
        RUN_TESTS: "OFF"
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_video_analytics:${EII_VERSION}
    container_name: ia_video_analytics
    hostname: ia_video_analytics
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    restart: unless-stopped
    ipc: "none"
    environment:
      AppName: "VideoAnalytics"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
    ports:
      - 65013:65013
    networks:
      - eii
    volumes:
      - "/var/tmp:/var/tmp"
      - "vol_eii_socket:${SOCKET_DIR}"
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # ion - VPU
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "/dev:/dev"
      - "/tmp:/tmp"
      - ./Certificates/VideoAnalytics:/run/secrets/VideoAnalytics:ro
      - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # NCS2 run - device-cgroup-rule='c 209:* rmw'
      # Selective rules can be applied for deployment
      - 'c 189:* rmw'
      - 'c 209:* rmw'
    devices:
      ## Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # ion - VPU
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "/dev:/dev"
